repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.3
    hooks:
      - id: isort
        types: [file, python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        types: [file, python]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs
  - repo: local
    hooks:
      - id: mypy
        name: Run mypy
        entry: mypy . --ignore-missing-imports
        pass_filenames: false
        language: system
        types: [python]
